baseURL = '/'
languageCode = 'en-us'
title = 'Huguette - A theme for Hugo'
copyright = "Copyright © :CURRENTYEAR: Cathelijne Hornstra"
enableGitInfo = "true"

theme = "huguette"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
[params]
  netlifycms = true
  css = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
